[2024-08-27T14:36:59.200+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-27T14:36:59.688+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_etl_dag.run_etl scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-27T14:36:59.696+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_etl_dag.run_etl scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-27T14:36:59.696+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-27T14:36:59.922+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_etl> on 2024-08-26 00:00:00+00:00
[2024-08-27T14:36:59.960+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-27T14:36:59.962+0000] {standard_task_runner.py:63} INFO - Started process 101 to run task
[2024-08-27T14:36:59.962+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_etl_dag', 'run_etl', 'scheduled__2024-08-26T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/youtube_etl_dag.py', '--cfg-path', '/tmp/tmpzv8tp_23']
[2024-08-27T14:36:59.964+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask run_etl
[2024-08-27T14:37:00.080+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_etl_dag.run_etl scheduled__2024-08-26T00:00:00+00:00 [running]> on host d18c1228ec21
[2024-08-27T14:37:00.472+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_etl_dag' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-26T00:00:00+00:00'
[2024-08-27T14:37:00.473+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-27T14:37:01.725+0000] {warnings.py:112} WARNING - /opt/***/dags/youtube_etl_dag.py:47: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfredshift['duración_minutos'] = dfredshift['duración'].apply(convert_to_minutes)

[2024-08-27T14:37:15.434+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-27T14:37:15.435+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-27T14:37:15.442+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=youtube_etl_dag, task_id=run_etl, run_id=scheduled__2024-08-26T00:00:00+00:00, execution_date=20240826T000000, start_date=20240827T143659, end_date=20240827T143715
[2024-08-27T14:37:15.753+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-27T14:37:15.766+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-27T14:37:15.854+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
